// COPYRIGHT (C) HARRY CLARK 2025
// DOCUMENTATION RESEARCH ON WORKING WITH MARIO KART WII'S MEMORY

// THE FOLLOWING PERTAINS TOWARDS THE BASE OF MEMORY ALLOCATION
// AND THE MODULARISATION ENCOMPASSING THE LOGIC BEHIND IT

// THIS FILE MORESO ENCOMPASSES THE EXTENSION METHODS USED TO BE 
// ABLE TO MAKE CONCLUSIVELY ASSERTIONS OF THE CHANGES IN MEMORY PROTECTION

using revoMem.Memory.Interfaces;

namespace revoMem.Memory;

public static class MemoryExtensions
{
    public static uint CHANGE_PROTECTION<T>(this T BASE, uint MEM_ADDRESS, int SIZE, MemoryProtection NEW_LEVEL)
    {
        return BASE.CHANGE_PROTECTION(MEM_ADDRESS, SIZE, NEW_LEVEL);
    }
}