// COPYRIGHT (C) HARRY CLARK 2025
// .NET IMPLEMENTATION OF MEMORY HOOKS AND MANAGEMENT

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF METHODS INDICATIVE OF
// SPECIFIC OS PROCESSES

namespace revoMem.Helpers;

public static partial class POSIXHelper
{
    
} 